language: c

dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - llvm-8-dev

env:
  global:
    - since="5195fdbcd9c318c2fa40463d25046a90ddca549a"

# TODO: Building testSlice.c is currently faked. This will be replaced by the slicing tool.
before_script:
  - echo "${since}"
  - ls /usr/lib/
  - ls /usr/lib/llvm-8/
  - ls /usr/lib/llvm-8/cmake
  - ./setupTests.sh
  - cp src/tests/unslicedTests.c src/tests/testSlice.c

script:
  - cmake .
  - make -j4
  - ./src/runTests
