language: c

dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - llvm-8-dev

env:
  global:
    - since="be1307c4399a1a978eadc4f9feb6a3d3c624696f" LLVM_PATH="/usr/lib/llvm-8/" LLVM_DIR="${LLVM_PATH}/cmake" LLVM_BIN="${LLVM_PATH}/bin"

# TODO: Building testSlice.c is currently faked. This will be replaced by the slicing tool.
before_script:
  - echo "old sha=${since}"
  - ./setupTests.sh
  - which opt || true
  - opt --version || true

script:
  - cmake .
  - make -j4
  - ./src/runTests
